/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#016b1c',
        'on-primary': '#ffffff',
        'primary-container': '#2a8533',
        'on-primary-container': '#f7fff1',
        'primary-fixed': '#9bf896',
        'primary-fixed-dim': '#7fdb7d',
        'on-primary-fixed': '#002204',
        'on-primary-fixed-variant': '#005313',
        'secondary': '#456741',
        'on-secondary': '#ffffff',
        'secondary-container': '#c3eaba',
        'on-secondary-container': '#496b45',
        'secondary-fixed': '#c6edbd',
        'secondary-fixed-dim': '#aad1a3',
        'on-secondary-fixed': '#022104',
        'on-secondary-fixed-variant': '#2e4e2b',
        'tertiary': '#9f345f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#be4d78',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffd9e2',
        'tertiary-fixed-dim': '#ffb0c8',
        'on-tertiary-fixed': '#3e001d',
        'on-tertiary-fixed-variant': '#831e4a',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f6fbf0',
        'on-background': '#171d16',
        'surface': '#f6fbf0',
        'on-surface': '#171d16',
        'surface-variant': '#dfe4d9',
        'on-surface-variant': '#3f493d',
        'outline': '#6f7a6c',
        'outline-variant': '#bfcab9',
        'surface-dim': '#d6dcd1',
        'surface-bright': '#f6fbf0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f5ea',
        'surface-container': '#eaf0e5',
        'surface-container-high': '#e4eadf',
        'surface-container-highest': '#dfe4d9',
        'inverse-surface': '#2c322b',
        'inverse-on-surface': '#edf3e7',
        'inverse-primary': '#7fdb7d',
        'surface-tint': '#066e1e',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
}
